version: 2.1

orbs:
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/asdf
  asdf: rynkowsg/asdf@0.1.1
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/checkout
  checkout: rynkowsg/checkout@0.1.6
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/rynkowsg
  rynkowsg: rynkowsg/rynkowsg@0.3.0

jobs:
  test:
    executor: rynkowsg/docker_x86_cimg_base
    steps:
      - checkout/checkout: {depth: 1}
      - asdf/install: {version: 0.14.0}
      - restore_cache:
          name: asdf - restore cache (partial)
          keys:
            - asdf-{{ checksum ".tool-versions" }}
      - run:
          name: asdf - add plugin
          command: |
            set -x
            cd /tmp
            git config --global advice.detachedHead false
            asdf plugin add bats https://github.com/timgluz/asdf-bats.git
            asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
            asdf plugin add shfmt https://github.com/luizm/asdf-shfmt.git
      - run:
          name: asdf - install tools
          command: |
            set -x
            asdf install
            bats --version
            shellcheck --version
            shfmt --version
      - save_cache:
          name: asdf - save cache (partial)
          key: asdf-{{ checksum ".tool-versions" }}
          paths:
            - ~/.asdf/installs
            - ~/.asdf/plugins
            - ~/.asdf/shims
      - run: make test
      - run: make lint
      - run: make format-check

workflows:
  main:
    jobs:
      - test
